# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True

import numpy as np
cimport numpy as cnp

cnp.import_array()

cdef extern from "math.h":
    double INFINITY


def insertion_by_cost(
    cnp.ndarray[cnp.int64_t, ndim=1] partial_tour,
    cnp.ndarray[cnp.int64_t, ndim=1] removed_vertices,
    cnp.ndarray[cnp.float64_t, ndim=2] cost_matrix,
):
    """
    C-level regret-1 insertion. Returns new tour as list (matching Python).
    """
    cdef:
        Py_ssize_t n = partial_tour.shape[0]
        Py_ssize_t k = removed_vertices.shape[0]
        Py_ssize_t n_nodes = cost_matrix.shape[0]
        Py_ssize_t current_len = n
        Py_ssize_t v_idx, pos, best_pos, i
        Py_ssize_t vertex, prev_node, next_node
        double best_cost, cost
        cnp.ndarray[cnp.int64_t, ndim=1] tour = np.empty(n + k, dtype=np.int64)
    
    # Copy initial tour
    for i in range(n):
        tour[i] = partial_tour[i]
    
    for v_idx in range(k):
        vertex = removed_vertices[v_idx]
        best_cost = INFINITY
        best_pos = 0
        
        for pos in range(current_len + 1):
            if pos > 0 and pos < current_len:
                prev_node = tour[pos - 1]
                next_node = tour[pos]
                cost = (cost_matrix[prev_node, vertex] + 
                        cost_matrix[vertex, next_node] - 
                        cost_matrix[prev_node, next_node])
            elif pos == 0:
                if current_len > 0:
                    cost = cost_matrix[vertex, tour[0]] - cost_matrix[tour[0], tour[0]]
                else:
                    cost = 0.0
            else:
                cost = cost_matrix[tour[current_len - 1], vertex]
            
            if cost < best_cost:
                best_cost = cost
                best_pos = pos
        
        # Shift elements right (memmove at C level)
        for i in range(current_len, best_pos, -1):
            tour[i] = tour[i - 1]
        tour[best_pos] = vertex
        current_len += 1
    
    # Return as Python list to match original behavior exactly
    return tour[:current_len].tolist()


def random_removal(
    cnp.ndarray[cnp.int64_t, ndim=1] tour,
    int omega,
    int num_depots,
    cnp.ndarray[cnp.int64_t, ndim=1] rng_indices,  # Pre-shuffled indices from Python RNG
):
    """
    C-level random removal. Returns (new_tour_list, removed_vertices_list).
    
    rng_indices: Random permutation of range(n_customers) generated by numpy RNG.
                 We take first omega of these to determine which customers to remove.
    """
    cdef:
        Py_ssize_t n = tour.shape[0]
        Py_ssize_t i, j, n_customers
        Py_ssize_t temp
        cnp.ndarray[cnp.int64_t, ndim=1] customer_positions
        cnp.ndarray[cnp.int64_t, ndim=1] removed_indices_arr
        cnp.ndarray[cnp.int64_t, ndim=1] new_tour
        cnp.ndarray[cnp.int64_t, ndim=1] removed_vertices
    
    # Count and collect customer positions (excluding depots)
    n_customers = 0
    for i in range(n):
        if tour[i] >= num_depots:
            n_customers += 1
    
    if n_customers <= omega:
        # Return copies as lists to match Python exactly
        return tour.copy().tolist(), []
    
    # Collect customer positions
    customer_positions = np.empty(n_customers, dtype=np.int64)
    j = 0
    for i in range(n):
        if tour[i] >= num_depots:
            customer_positions[j] = i
            j += 1
    
    # Use pre-shuffled rng_indices to select which customers to remove
    # rng_indices should be a permutation of [0, 1, ..., n_customers-1]
    removed_indices_arr = np.empty(omega, dtype=np.int64)
    for i in range(omega):
        removed_indices_arr[i] = customer_positions[rng_indices[i]]
    
    # Sort descending for removal (pop from end to avoid index shifting)
    # Simple insertion sort for small omega
    for i in range(1, omega):
        temp = removed_indices_arr[i]
        j = i - 1
        while j >= 0 and removed_indices_arr[j] < temp:
            removed_indices_arr[j + 1] = removed_indices_arr[j]
            j -= 1
        removed_indices_arr[j + 1] = temp
    
    # Build new tour by masking out removed indices
    # Use a boolean mask approach
    cdef cnp.ndarray[cnp.uint8_t, ndim=1, cast=True] mask = np.ones(n, dtype=np.uint8)
    for i in range(omega):
        mask[removed_indices_arr[i]] = 0
    
    new_tour = np.empty(n - omega, dtype=np.int64)
    j = 0
    for i in range(n):
        if mask[i]:
            new_tour[j] = tour[i]
            j += 1
    
    # Extract removed vertices in the order of removed_indices (descending)
    removed_vertices = np.empty(omega, dtype=np.int64)
    for i in range(omega):
        removed_vertices[i] = tour[removed_indices_arr[i]]
    
    return new_tour.tolist(), removed_vertices.tolist()